version: '3'

services:
    db: 
        container_name: db
        image: bitnami/postgresql:15.4.0
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRESQL_USERNAME=dev
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=picpay
        volumes:
            - postgres_data:/bitnami/postgresql

volumes:
    postgres_data:
        driver: local